# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: command.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'command.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcommand.proto\x12\x10\x63om.sexToy.proto\"\x83\x01\n\rDeviceCommand\x12\x14\n\x0c\x64\x65vice_token\x18\x01 \x01(\t\x12\x33\n\x0c\x63ommand_type\x18\x02 \x01(\x0e\x32\x1d.com.sexToy.proto.CommandType\x12\x14\n\x0c\x63ommand_data\x18\x03 \x01(\x0c\x12\x11\n\ttimestamp\x18\x04 \x01(\x04*]\n\x0b\x43ommandType\x12\x17\n\x13\x43OMMAND_UNSPECIFIED\x10\x00\x12\x11\n\rCOMMAND_START\x10\x01\x12\x10\n\x0c\x43OMMAND_STOP\x10\x02\x12\x10\n\x0c\x43OMMAND_TASK\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'command_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMMANDTYPE']._serialized_start=169
  _globals['_COMMANDTYPE']._serialized_end=262
  _globals['_DEVICECOMMAND']._serialized_start=36
  _globals['_DEVICECOMMAND']._serialized_end=167
# @@protoc_insertion_point(module_scope)
