# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: device.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x64\x65vice.proto\x12\rdevice_motion\"\xb1\x01\n\x13\x44\x65viceMotionMessage\x12.\n\x06\x63onfig\x18\x01 \x01(\x0b\x32\x1c.device_motion.ConfigMessageH\x00\x12\x30\n\x07session\x18\x02 \x01(\x0b\x32\x1d.device_motion.SessionMessageH\x00\x12\x30\n\x07\x63ontrol\x18\x03 \x01(\x0b\x32\x1d.device_motion.ControlMessageH\x00\x42\x06\n\x04\x62ody\"\xbb\x02\n\x08Movement\x12\x34\n\tdirection\x18\x01 \x01(\x0e\x32!.device_motion.Movement.Direction\x12\x10\n\x08\x64istance\x18\x02 \x01(\x02\x12\x10\n\x08\x64uration\x18\x03 \x01(\x02\x12\x10\n\x08rotation\x18\x04 \x01(\x02\x12\x45\n\x12rotation_direction\x18\x05 \x01(\x0e\x32).device_motion.Movement.RotationDirection\"1\n\tDirection\x12\x12\n\x0e\x44IRECTION_DOWN\x10\x00\x12\x10\n\x0c\x44IRECTION_UP\x10\x01\"I\n\x11RotationDirection\x12\x15\n\x11ROT_DIR_CLOCKWISE\x10\x00\x12\x1d\n\x19ROT_DIR_COUNTER_CLOCKWISE\x10\x01\"M\n\tPrimitive\x12\x14\n\x0cprimitive_id\x18\x01 \x01(\t\x12*\n\tmovements\x18\x02 \x03(\x0b\x32\x17.device_motion.Movement\"=\n\rConfigMessage\x12,\n\nprimitives\x18\x01 \x03(\x0b\x32\x18.device_motion.Primitive\"B\n\x04Unit\x12\x14\n\x0cprimitive_id\x18\x01 \x01(\t\x12\x11\n\titeration\x18\x02 \x01(\x05\x12\x11\n\tintensity\x18\x03 \x01(\x02\"4\n\x0eSessionMessage\x12\"\n\x05units\x18\x01 \x03(\x0b\x32\x13.device_motion.Unit\"\xe6\x01\n\x0e\x43ontrolMessage\x12\x36\n\x07\x63ommand\x18\x01 \x01(\x0e\x32%.device_motion.ControlMessage.Command\x12\x11\n\tintensity\x18\x02 \x01(\x02\x12\x10\n\x08\x64uration\x18\x03 \x01(\x02\"w\n\x07\x43ommand\x12\x17\n\x13\x43OMMAND_UNSPECIFIED\x10\x00\x12\x11\n\rCOMMAND_RESET\x10\x01\x12\x11\n\rCOMMAND_PAUSE\x10\x02\x12\x12\n\x0e\x43OMMAND_RESUME\x10\x03\x12\x19\n\x15\x43OMMAND_SET_INTENSITY\x10\x04\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'device_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DEVICEMOTIONMESSAGE._serialized_start=32
  _DEVICEMOTIONMESSAGE._serialized_end=209
  _MOVEMENT._serialized_start=212
  _MOVEMENT._serialized_end=527
  _MOVEMENT_DIRECTION._serialized_start=403
  _MOVEMENT_DIRECTION._serialized_end=452
  _MOVEMENT_ROTATIONDIRECTION._serialized_start=454
  _MOVEMENT_ROTATIONDIRECTION._serialized_end=527
  _PRIMITIVE._serialized_start=529
  _PRIMITIVE._serialized_end=606
  _CONFIGMESSAGE._serialized_start=608
  _CONFIGMESSAGE._serialized_end=669
  _UNIT._serialized_start=671
  _UNIT._serialized_end=737
  _SESSIONMESSAGE._serialized_start=739
  _SESSIONMESSAGE._serialized_end=791
  _CONTROLMESSAGE._serialized_start=794
  _CONTROLMESSAGE._serialized_end=1024
  _CONTROLMESSAGE_COMMAND._serialized_start=905
  _CONTROLMESSAGE_COMMAND._serialized_end=1024
# @@protoc_insertion_point(module_scope)
